# Generated by Django 3.2 on 2022-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20221004_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
