# Generated by Django 3.2 on 2022-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=True, max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
