# Generated by Django 3.2 on 2022-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_wordd_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='complete',
        ),
    ]
